service: sls-vpc-example

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  versionFunctions: false
  logRetentionInDays: 1
  deploymentBucket:
    serverSideEncryption: AES256
  endpointType: regional
  vpc:
    securityGroupIds:
      - Ref: LambdaExecutionSecurityGroup
    subnetIds:
      - Ref: AppSubnet1
      - Ref: AppSubnet2
      - Ref: AppSubnet3
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 's3:PutObject'
      Resource:
        'Fn::Join':
          - ''
          - - 'arn:aws:s3:::'
            - Ref: TestBucket
            - '/*'

plugins:
  - serverless-vpc-plugin

package:
  individually: true
  excludeDevDependencies: true
  exclude:
    - .npmrc
    - package*.json
    - resources/**
    - node_modules/**

custom:
  vpcConfig:
    cidrBlock: '10.0.0.0/16'
    createNatGateway: false
    createDbSubnet: true
    createNetworkAcl: true
    zones:
      - us-east-1a
      - us-east-1b
      - us-east-1c
    services:
      - s3

functions:
  s3:
    handler: s3.handler
    description: S3 Test Handler
    environment:
      BUCKET_NAME:
        Ref: TestBucket

resources:
  - ${file(resources/s3_cf.yml)}
